var jokes = [
  `Did you hear they arrested the devil? Yeah, they got him on possession.`,
  `What did one DNA say to the other DNA? “Do these genes make me look fat?”`,
  `My IQ test results came back. They were negative.`,
  `What do you get when you cross a polar bear with a seal? A polar bear.`,
  `Why can’t you trust an atom? Because they make up literally everything.`,
  `Why was six afraid of seven? Because seven eight nine.`,
  `What do you call a hippie’s wife? Mississippi.`,
  `What’s the difference between an outlaw and an in-law? Outlaws are wanted.`,
  `Scientists have recently discovered a food that greatly reduces sex drive. It’s called wedding cake.`,
  ` Before you marry a person, you should first make them use a computer with a slow Internet connection to see who they really are.`,
  ` I never knew what happiness was until I got married—and then it was too late.`,
  ` Some men say they don’t wear their wedding band because it cuts off circulation. Well, that’s the point, isn’t it?`,

  ` Advice to husbands: Try praising your wife now and then, even if it does startle her at first.`,

  ` Did you hear about the shepherd who drove his sheep through town? He was given a ticket for making a ewe tur`,
  ` What happens to an illegally parked frog? It gets toad awa`,
  ` How does the man in the moon get his hair cut? Eclipse i`,
  ` What do you call a blonde with half a brain? Gifte`,
  ` Why are so many blonde jokes one-liners? So brunettes can remember the`,
  ` Our child has a great deal of willpower—and even more won’t powe`,
  ` Among the things that are so simple even a child can operate them are parent`,
  ` Why aren’t dogs good dancers? Because they have two left fee`,
  `Whats a dogs favorite homework assignment? A lab repor`,
  ` Why did Beethoven get rid of his chickens? All they said was, “Bach, Bach, Bach `,
  ` Of course I wouldn’t say anything about her unless I could say something good. And, oh boy, is this good`,
  ` When he talks, it isn’t a conversation. It’s a filibuste`,
  ` She leaves me with the feeling that when we bury the hatchet she’ll mark the exact spo`,
  ` You can’t believe everything you hear—but you can repeat i`,
  ` There’s a lot to be said in his favor, but it’s not nearly as interestin`,
  ` They’ve been treating me like one of the family, and I’ve put up with it for as long as I ca`,
  ` Why did the parents not like their son’s biology teacher? He had skeletons in his close`,
  ` Their first daughter was born with a silver spoon in her mouth. Now they’re hoping for triplets so they ca`,
  ` I spent a lot of time, money and effort childproofing my house … but the kids still get i`,
  ` Small son sitting on Daddy’s lap: “I’m still confused. Was I born in a nest or a hive`,
  ` A Freudian slip is when you say one thing but mean your mothe`,
  ` My mother was so surprised when I told her I was born again. She said she didn’t feel a thin`,
  ` What do you call a bear with no teeth? A gummy bea`,
  ` What did one cannibal say to the other while they were eating a clown? “Does this taste funny to you`,
  ` What do you call a mobster who’s buried in cement? A hardened crimina`,
  ` What do fish say when they hit a concrete wall? Da`,
  ` What do you need in order to make a small fortune on Wall Street? A large fortun`,
  ` One of the oddities of Wall Street is that the dealer, not the customer, is the broke`,
  `A rich man is one who isn’t afraid to ask the clerk to show him something cheape`,
  ` If you take $2 out of an ATM that has a $2.50 fee, do you owe the machine mone`,
  ` Knock, knock. Who’s there? Nobel. Nobel who? No­bel, so I knock knocke Knock, knock. Who’s there? Alabama. Anybody with you? Nope. I’m Alabama sel`,
  ` Knock, knock. Who’s there? Ayatollah. Ayatollah who? Ayatollah you alread`,
  ` Knock, knock. Who’s there? Control freak. Now you say, “Control freak who`,
  ` The reason some politicians like to stand on their record is to keep voters from examining i`,
  ` The insomnia patient was such a fervent vegetarian that he counted carrots jumping over a fenc`,
  ` My father is allergic to cotton. He has pills he can take, but he can’t get them out of the bottl`,
  ` You’ll always stay young if you live honestly, eat slowly, sleep sufficiently, work industriously, worship faithfully and lie about your ag`,
  ` How can you tell you’re getting old? When you go to an antique auction and three people bid on yo`,
  ` the nurse who was chewed out by the doctor because she was absent without gauz`,
  ` the crustacean accused of promoting his own shellfish interest`,
  ` the cat who ate a ball of yarn? She had mitten`,
  ` the kid who started a business tying shoelaces on the playground? It was a knot-for-profi`,
  ` the claustrophobic astronaut? He just wanted a little more spac`,
];
// let joke;

function telljokes() {
  var joke = Math.floor(Math.random() * jokes.length);
  console.log("\n------->");
  document.write(jokes[joke]);
}
